// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web Firebase Options
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqNP6dP0TGJxLzsxmeyb1L3OALQIdUTM',
    appId: '1:251119518452:web:ed34fa54a5ad6cee0614a1',
    messagingSenderId: '251119518452',
    projectId: 'freight-transport-f8a55',
    authDomain: 'freight-transport-f8a55.firebaseapp.com',
    storageBucket: 'freight-transport-f8a55.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX', // Replace with your measurementId if using analytics
  );

  // Android Firebase Options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpqNP6dP0TGJxLzsxmeyb1L3OALQIdUTM',
    appId: '1:251119518452:android:ed34fa54a5ad6cee0614a1',
    messagingSenderId: '251119518452',
    projectId: 'freight-transport-f8a55',
    storageBucket: 'freight-transport-f8a55.firebasestorage.app',
  );

  // iOS Firebase Options
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpqNP6dP0TGJxLzsxmeyb1L3OALQIdUTM', // Replace with iOS API key if different
    appId: '1:251119518452:ios:ed34fa54a5ad6cee0614a1', // Replace with your iOS appId
    messagingSenderId: '251119518452',
    projectId: 'freight-transport-f8a55',
    storageBucket: 'freight-transport-f8a55.firebasestorage.app',
    iosBundleId: 'com.example.freight', // Your iOS bundle ID
  );

  // macOS Firebase Options
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpqNP6dP0TGJxLzsxmeyb1L3OALQIdUTM', // Replace if needed
    appId: '1:251119518452:macos:ed34fa54a5ad6cee0614a1', // Replace with your macOS appId
    messagingSenderId: '251119518452',
    projectId: 'freight-transport-f8a55',
    storageBucket: 'freight-transport-f8a55.firebasestorage.app',
    iosBundleId: 'com.example.freight',
  );
}